name: Node.js CI
run-name: ${{ github.actor }} is testing out GitHub Actions Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm create vite .
#      - run: npm i vitest
#       - run: npm install -g typescript
#       - run: npm run build
#      - run: npm test


