name: JSON-SERVER
run-name: ${{ github.actor }} is testing out GitHub Actions JSON-SERVER

on: 
  push:
    paths-ignore:
      - 'src/**/*.test.tsx'

jobs:
  job1:
      runs-on: windows-latest
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm create vite .
        - run: npm i -g typescript
        - run: npm i vitest
        - run: npm test
